# Generated by Django 4.0.5 on 2023-01-01 07:06

import basicapi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('top_image', models.ImageField(blank=True, null=True, upload_to=basicapi.models.top_image_upload_path, verbose_name='トップ画像')),
                ('nickname', models.CharField(max_length=20, verbose_name='ニックネーム')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('location', models.CharField(blank=True, choices=[('hokkaido', '北海道'), ('tohoku', '東北'), ('kanto', '関東'), ('hokuriku', '北陸'), ('chubu', '中部'), ('kansai', '関西'), ('chugoku', '中国'), ('shikoku', '四国'), ('kyushu', '九州')], max_length=32, null=True, verbose_name='出身地')),
                ('hobby', models.CharField(blank=True, max_length=32, null=True, verbose_name='趣味')),
                ('tweet', models.CharField(blank=True, max_length=10, null=True, verbose_name='一言')),
                ('introduction', models.TextField(blank=True, max_length=1000, null=True, verbose_name='自己紹介')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
