# Generated by Django 4.0.2 on 2023-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0005_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_quit',
            field=models.BooleanField(default=False),
        ),
    ]
